Created new module CaseManager.js
johan1505/CS180Project pull request #66
Opened 2020-05-12 00:41 UTC by Mari-Hayashi

Created Server/modules/CaseManager.js, which handles all operations regarding the case data.

2020-05-12 02:17 UTC, johan1505 requested changes

2020-05-12 02:17 UTC, johan1505 commented on src/Server/modules/CaseManager.js
> +	const classesModule = require('../modules/DataClasses.js');
I think  you can move this import to the top of the file (line 4)

2020-05-12 02:17 UTC, johan1505 commented on src/Server/modules/CaseManager.js
> +	} else if (req.query.TypeOfData == 2) {
I think you meant TypeOfData here

2020-05-12 02:17 UTC, johan1505 commented on src/Server/modules/CaseManager.js
> +	const ageReq = require('../modules/DataClasses.js');
This could go to the top too

2020-05-13 21:28 UTC, vtruo009 approved these changes

2020-05-14 02:23 UTC, johan1505 approved these changes

2020-05-14 03:25 UTC, merged